services:
  webapi:
    deploy:
      resources:
        limits:
          cpus: "1.0"    # Limit to one CPU core
          memory: 200M # Limit to 200MB of memory
        reservations:
          cpus: "1.0"
          memory: 200M
    build:
      context: ../
      dockerfile: MetaExchange.WebApi/Dockerfile
    ports:
      - "4523:80"      # HTTP
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      
